version: "3.9"
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile_local
    command: python spending_tracker/manage.py runserver 0.0.0.0:8000
    image: spending-tracker-web
    volumes:
      - ..:/app
    env_file:
      - ./.env.local
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: on-failure:5
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - spending_tracker_db_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: on-failure:5
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  spending_tracker_db_data: