# Generated by Django 4.2 on 2023-04-23 06:34

from django.db import migrations, models
import django.db.models.deletion
import ledger.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_num', models.CharField(default=ledger.models.generate_random_id, max_length=256, unique=True)),
                ('source', models.CharField(max_length=256)),
                ('trans_date', models.DateTimeField()),
                ('name', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.transaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.type')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.ManyToManyField(through='ledger.TransactionType', to='ledger.type'),
        ),
        migrations.AddConstraint(
            model_name='transactiontype',
            constraint=models.UniqueConstraint(fields=('transaction', 'type'), name='unique transaction type'),
        ),
    ]
