# Generated by Django 4.2 on 2023-04-30 00:51

from django.db import migrations, models
import ledger.models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_transaction_creator_alter_type_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ref_num',
            field=models.CharField(default=ledger.models.generate_random_id, max_length=256),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('creator', 'ref_num'), name='unique creator ref_num '),
        ),
    ]
