# Generated by Django 4.2 on 2023-04-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_remove_transaction_unique_creator_ref_num__and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
